# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ui_operations_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 739)
        Dialog.setStyleSheet("#MainWidget {\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4a4a4a;\n"
"    background-color: rgb(40, 44, 52);\n"
"}")
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainWidget = QtWidgets.QWidget(Dialog)
        self.MainWidget.setStyleSheet("#MainWidget {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #4a4a4a;\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"\n"
"#NewCategoryPage,\n"
"#EmptyCodePage,\n"
"#NewArticlePage, \n"
"#EditArticlePage,\n"
"#EntreePage,\n"
"#SortiePage,\n"
"#ConfirmPage,\n"
"\n"
"#LoginPage,\n"
"#NewUserPage,\n"
"#EditUserPage,\n"
"#ChangePasswordPage,\n"
"\n"
"#NewCommandPage,\n"
"#EditCommandPage\n"
"{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 11pt \"Monaco\";\n"
"}\n"
"\n"
"#line, #line_2 {\n"
"    background-color: #4a4a4a;\n"
"}\n"
"/* ----------------------------------------------------------------*/\n"
"QLabel {\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"#titleLabel {\n"
"    padding: 10px;\n"
"    min-height: 70px;\n"
"    font-size: 20pt;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"#labelCategoryError,\n"
"#labelEmptyCodeError,\n"
"#labelNewError,\n"
"#labelEditError,\n"
"#labelEntreeError,\n"
"#labelSortieError,\n"
"\n"
"#labelLoginErrors,\n"
"#labelAddUserErrors,\n"
"#labelEditUserErrors,\n"
"#labelChangePassErrors,\n"
"\n"
"#labelCommandError,\n"
"#labelEditCommandError {    \n"
"    color: #e55039;\n"
"    padding: 10px 0px;\n"
"}\n"
"\n"
"#confirmLabelMessage {        \n"
"    font-size: 14pt;    \n"
"    color: rgb(237, 51, 59);\n"
"}\n"
"\n"
"QLineEdit, \n"
"QSpinBox, \n"
"QDoubleSpinBox, \n"
"QDateEdit\n"
"{\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    min-height: 30px;\n"
"    min-width: 300px;\n"
"    font-size: 12pt;\n"
"}\n"
"QLineEdit:hover,\n"
"QSpinBox:hover,\n"
"QDoubleSpinBox:hover,\n"
"QDateEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus,\n"
"QSpinbox:focus,\n"
"QSpinBox:focus,\n"
"QDateEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QLineEdit:enabled, \n"
"QSpinBox:enabled, \n"
"QDoubleSpinBox:enabled,\n"
"QDateEdit:enabled {\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    min-width: 300px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    min-height: 35px;\n"
"    min-width: 45px;\n"
"    font-size: 12pt;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton:!enabled {\n"
"    color: #ccc;\n"
"    background-color: rgb(33, 37, 43);\n"
"}")
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout_13.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.contentTopBg = QtWidgets.QFrame(self.MainWidget)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 0))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(49, 39))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_4.addWidget(self.closeAppBtn)
        self.horizontalLayout_2.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addWidget(self.contentTopBg)
        self.titleLabel = QtWidgets.QLabel(self.MainWidget)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 90))
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleLabel.setLineWidth(0)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_13.addWidget(self.titleLabel)
        self.line_2 = QtWidgets.QFrame(self.MainWidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_13.addWidget(self.line_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.MainWidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.NewCategoryPage = QtWidgets.QWidget()
        self.NewCategoryPage.setObjectName("NewCategoryPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.NewCategoryPage)
        self.verticalLayout_7.setContentsMargins(5, 15, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.NewCategoryPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setHorizontalSpacing(20)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lineEditCatName = QtWidgets.QLineEdit(self.widget)
        self.lineEditCatName.setObjectName("lineEditCatName")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCatName)
        self.labelCategoryError = QtWidgets.QLabel(self.widget)
        self.labelCategoryError.setObjectName("labelCategoryError")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelCategoryError)
        self.btnSaveNewCat = QtWidgets.QPushButton(self.widget)
        self.btnSaveNewCat.setIconSize(QtCore.QSize(25, 25))
        self.btnSaveNewCat.setObjectName("btnSaveNewCat")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnSaveNewCat)
        self.verticalLayout_7.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 408, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.stackedWidget.addWidget(self.NewCategoryPage)
        self.EmptyCodePage = QtWidgets.QWidget()
        self.EmptyCodePage.setObjectName("EmptyCodePage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.EmptyCodePage)
        self.verticalLayout_14.setContentsMargins(5, 15, 5, 15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_2 = QtWidgets.QWidget(self.EmptyCodePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.formLayout_9 = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setHorizontalSpacing(20)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_31 = QtWidgets.QLabel(self.widget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.labelEmptyCodeError = QtWidgets.QLabel(self.widget_2)
        self.labelEmptyCodeError.setObjectName("labelEmptyCodeError")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelEmptyCodeError)
        self.cbBoxCatEmptyCode = QtWidgets.QComboBox(self.widget_2)
        self.cbBoxCatEmptyCode.setObjectName("cbBoxCatEmptyCode")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbBoxCatEmptyCode)
        self.verticalLayout_14.addWidget(self.widget_2)
        self.plainTextEditEmptyCodeResult = QtWidgets.QPlainTextEdit(self.EmptyCodePage)
        self.plainTextEditEmptyCodeResult.setMinimumSize(QtCore.QSize(0, 200))
        self.plainTextEditEmptyCodeResult.setObjectName("plainTextEditEmptyCodeResult")
        self.verticalLayout_14.addWidget(self.plainTextEditEmptyCodeResult)
        self.btnSearchEmptyCode = QtWidgets.QPushButton(self.EmptyCodePage)
        self.btnSearchEmptyCode.setIconSize(QtCore.QSize(25, 25))
        self.btnSearchEmptyCode.setObjectName("btnSearchEmptyCode")
        self.verticalLayout_14.addWidget(self.btnSearchEmptyCode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 234, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.EmptyCodePage)
        self.NewArticlePage = QtWidgets.QWidget()
        self.NewArticlePage.setMinimumSize(QtCore.QSize(0, 0))
        self.NewArticlePage.setObjectName("NewArticlePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.NewArticlePage)
        self.verticalLayout_2.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formFrame = QtWidgets.QFrame(self.NewArticlePage)
        self.formFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.formFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.formFrame)
        self.label_9.setMinimumSize(QtCore.QSize(0, 31))
        self.label_9.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cbBoxCatNew = QtWidgets.QComboBox(self.formFrame)
        self.cbBoxCatNew.setMinimumSize(QtCore.QSize(319, 31))
        self.cbBoxCatNew.setObjectName("cbBoxCatNew")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbBoxCatNew)
        self.label = QtWidgets.QLabel(self.formFrame)
        self.label.setMinimumSize(QtCore.QSize(0, 31))
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditCodeNew = QtWidgets.QLineEdit(self.formFrame)
        self.lineEditCodeNew.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditCodeNew.setStyleSheet("selection-color: rgb(255, 0, 0);")
        self.lineEditCodeNew.setFrame(True)
        self.lineEditCodeNew.setObjectName("lineEditCodeNew")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditCodeNew)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 31))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditDesigNew = QtWidgets.QLineEdit(self.formFrame)
        self.lineEditDesigNew.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditDesigNew.setObjectName("lineEditDesigNew")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditDesigNew)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 31))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditRefNew = QtWidgets.QLineEdit(self.formFrame)
        self.lineEditRefNew.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditRefNew.setObjectName("lineEditRefNew")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditRefNew)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        self.label_4.setMinimumSize(QtCore.QSize(0, 31))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditUMNew = QtWidgets.QLineEdit(self.formFrame)
        self.lineEditUMNew.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditUMNew.setObjectName("lineEditUMNew")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditUMNew)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 31))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditEmpNew = QtWidgets.QLineEdit(self.formFrame)
        self.lineEditEmpNew.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditEmpNew.setObjectName("lineEditEmpNew")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditEmpNew)
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        self.label_6.setMinimumSize(QtCore.QSize(0, 31))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBoxQteNew = QtWidgets.QSpinBox(self.formFrame)
        self.spinBoxQteNew.setMinimumSize(QtCore.QSize(314, 34))
        self.spinBoxQteNew.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxQteNew.setMinimum(1)
        self.spinBoxQteNew.setMaximum(10000)
        self.spinBoxQteNew.setObjectName("spinBoxQteNew")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxQteNew)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        self.label_7.setMinimumSize(QtCore.QSize(0, 31))
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.dSBoxPrixNew = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.dSBoxPrixNew.setMinimumSize(QtCore.QSize(314, 34))
        self.dSBoxPrixNew.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dSBoxPrixNew.setProperty("showGroupSeparator", False)
        self.dSBoxPrixNew.setDecimals(2)
        self.dSBoxPrixNew.setMaximum(100000000000000.0)
        self.dSBoxPrixNew.setObjectName("dSBoxPrixNew")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dSBoxPrixNew)
        self.label_10 = QtWidgets.QLabel(self.formFrame)
        self.label_10.setMinimumSize(QtCore.QSize(0, 31))
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.textEditObsNew = QtWidgets.QPlainTextEdit(self.formFrame)
        self.textEditObsNew.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEditObsNew.setObjectName("textEditObsNew")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.textEditObsNew)
        self.btnSaveNewArticle = QtWidgets.QPushButton(self.formFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveNewArticle.setIcon(icon1)
        self.btnSaveNewArticle.setIconSize(QtCore.QSize(22, 22))
        self.btnSaveNewArticle.setObjectName("btnSaveNewArticle")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.btnSaveNewArticle)
        self.labelNewError = QtWidgets.QLabel(self.formFrame)
        self.labelNewError.setMinimumSize(QtCore.QSize(0, 0))
        self.labelNewError.setStyleSheet("color: rgb(239, 41, 41);")
        self.labelNewError.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelNewError.setWordWrap(True)
        self.labelNewError.setObjectName("labelNewError")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.labelNewError)
        self.verticalLayout_2.addWidget(self.formFrame)
        self.stackedWidget.addWidget(self.NewArticlePage)
        self.EditArticlePage = QtWidgets.QWidget()
        self.EditArticlePage.setObjectName("EditArticlePage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.EditArticlePage)
        self.verticalLayout_4.setContentsMargins(10, 15, 10, 15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.EditArticlePage)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnEditArticle = QtWidgets.QPushButton(self.frame)
        self.btnEditArticle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/box--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditArticle.setIcon(icon2)
        self.btnEditArticle.setIconSize(QtCore.QSize(25, 25))
        self.btnEditArticle.setObjectName("btnEditArticle")
        self.horizontalLayout_10.addWidget(self.btnEditArticle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.btnSaveEditArticle = QtWidgets.QPushButton(self.frame)
        self.btnSaveEditArticle.setEnabled(False)
        self.btnSaveEditArticle.setMinimumSize(QtCore.QSize(49, 39))
        self.btnSaveEditArticle.setText("")
        self.btnSaveEditArticle.setIcon(icon1)
        self.btnSaveEditArticle.setIconSize(QtCore.QSize(25, 25))
        self.btnSaveEditArticle.setDefault(True)
        self.btnSaveEditArticle.setObjectName("btnSaveEditArticle")
        self.horizontalLayout_10.addWidget(self.btnSaveEditArticle)
        self.verticalLayout_4.addWidget(self.frame)
        self.formFrame_2 = QtWidgets.QFrame(self.EditArticlePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame_2.sizePolicy().hasHeightForWidth())
        self.formFrame_2.setSizePolicy(sizePolicy)
        self.formFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.formFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formFrame_2.setObjectName("formFrame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formFrame_2)
        self.formLayout_2.setContentsMargins(0, 5, 5, 5)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formFrame_2)
        self.label_8.setMinimumSize(QtCore.QSize(126, 0))
        self.label_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cbBoxCatEdit = QtWidgets.QComboBox(self.formFrame_2)
        self.cbBoxCatEdit.setObjectName("cbBoxCatEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbBoxCatEdit)
        self.label_11 = QtWidgets.QLabel(self.formFrame_2)
        self.label_11.setMinimumSize(QtCore.QSize(126, 0))
        self.label_11.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEditCodeEdit = QtWidgets.QLineEdit(self.formFrame_2)
        self.lineEditCodeEdit.setEnabled(True)
        self.lineEditCodeEdit.setObjectName("lineEditCodeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditCodeEdit)
        self.label_12 = QtWidgets.QLabel(self.formFrame_2)
        self.label_12.setMinimumSize(QtCore.QSize(126, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEditDesigEdit = QtWidgets.QLineEdit(self.formFrame_2)
        self.lineEditDesigEdit.setObjectName("lineEditDesigEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditDesigEdit)
        self.label_13 = QtWidgets.QLabel(self.formFrame_2)
        self.label_13.setMinimumSize(QtCore.QSize(126, 0))
        self.label_13.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEditRefEdit = QtWidgets.QLineEdit(self.formFrame_2)
        self.lineEditRefEdit.setObjectName("lineEditRefEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditRefEdit)
        self.label_14 = QtWidgets.QLabel(self.formFrame_2)
        self.label_14.setMinimumSize(QtCore.QSize(126, 0))
        self.label_14.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEditEmpEdit = QtWidgets.QLineEdit(self.formFrame_2)
        self.lineEditEmpEdit.setObjectName("lineEditEmpEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditEmpEdit)
        self.label_15 = QtWidgets.QLabel(self.formFrame_2)
        self.label_15.setMinimumSize(QtCore.QSize(126, 0))
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEditUMEdit = QtWidgets.QLineEdit(self.formFrame_2)
        self.lineEditUMEdit.setObjectName("lineEditUMEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditUMEdit)
        self.label_16 = QtWidgets.QLabel(self.formFrame_2)
        self.label_16.setMinimumSize(QtCore.QSize(126, 0))
        self.label_16.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.spinBoxQteEdit = QtWidgets.QSpinBox(self.formFrame_2)
        self.spinBoxQteEdit.setEnabled(True)
        self.spinBoxQteEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxQteEdit.setObjectName("spinBoxQteEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxQteEdit)
        self.label_17 = QtWidgets.QLabel(self.formFrame_2)
        self.label_17.setMinimumSize(QtCore.QSize(126, 0))
        self.label_17.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.dSBoxPrixEdit = QtWidgets.QDoubleSpinBox(self.formFrame_2)
        self.dSBoxPrixEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dSBoxPrixEdit.setMaximum(1000000000.0)
        self.dSBoxPrixEdit.setObjectName("dSBoxPrixEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dSBoxPrixEdit)
        self.label_18 = QtWidgets.QLabel(self.formFrame_2)
        self.label_18.setMinimumSize(QtCore.QSize(126, 0))
        self.label_18.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.dSBoxValeurEdit = QtWidgets.QDoubleSpinBox(self.formFrame_2)
        self.dSBoxValeurEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dSBoxValeurEdit.setMaximum(10000000000.0)
        self.dSBoxValeurEdit.setObjectName("dSBoxValeurEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dSBoxValeurEdit)
        self.label_19 = QtWidgets.QLabel(self.formFrame_2)
        self.label_19.setMinimumSize(QtCore.QSize(126, 0))
        self.label_19.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.textEditObsEdit = QtWidgets.QPlainTextEdit(self.formFrame_2)
        self.textEditObsEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEditObsEdit.setObjectName("textEditObsEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.textEditObsEdit)
        self.labelArticleId = QtWidgets.QLabel(self.formFrame_2)
        self.labelArticleId.setEnabled(True)
        self.labelArticleId.setText("")
        self.labelArticleId.setObjectName("labelArticleId")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelArticleId)
        self.labelEditError = QtWidgets.QLabel(self.formFrame_2)
        self.labelEditError.setMinimumSize(QtCore.QSize(0, 0))
        self.labelEditError.setObjectName("labelEditError")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.labelEditError)
        self.verticalLayout_4.addWidget(self.formFrame_2)
        self.stackedWidget.addWidget(self.EditArticlePage)
        self.EntreePage = QtWidgets.QWidget()
        self.EntreePage.setObjectName("EntreePage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.EntreePage)
        self.verticalLayout_3.setContentsMargins(10, 15, 10, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formFrame_3 = QtWidgets.QFrame(self.EntreePage)
        self.formFrame_3.setObjectName("formFrame_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formFrame_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_20 = QtWidgets.QLabel(self.formFrame_3)
        self.label_20.setMinimumSize(QtCore.QSize(85, 0))
        self.label_20.setMaximumSize(QtCore.QSize(79, 30))
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.formFrame_3)
        self.label_21.setMinimumSize(QtCore.QSize(85, 0))
        self.label_21.setMaximumSize(QtCore.QSize(79, 30))
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.lineEditEntreeCode = QtWidgets.QLineEdit(self.formFrame_3)
        self.lineEditEntreeCode.setEnabled(False)
        self.lineEditEntreeCode.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditEntreeCode.setReadOnly(True)
        self.lineEditEntreeCode.setObjectName("lineEditEntreeCode")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditEntreeCode)
        self.label_22 = QtWidgets.QLabel(self.formFrame_3)
        self.label_22.setMinimumSize(QtCore.QSize(85, 0))
        self.label_22.setMaximumSize(QtCore.QSize(79, 30))
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.spBoxEntreeQte = QtWidgets.QSpinBox(self.formFrame_3)
        self.spBoxEntreeQte.setMinimumSize(QtCore.QSize(314, 34))
        self.spBoxEntreeQte.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spBoxEntreeQte.setMinimum(1)
        self.spBoxEntreeQte.setMaximum(1000000000)
        self.spBoxEntreeQte.setObjectName("spBoxEntreeQte")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spBoxEntreeQte)
        self.label_23 = QtWidgets.QLabel(self.formFrame_3)
        self.label_23.setMinimumSize(QtCore.QSize(85, 0))
        self.label_23.setMaximumSize(QtCore.QSize(79, 30))
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.btnSaveEntree = QtWidgets.QPushButton(self.formFrame_3)
        self.btnSaveEntree.setMinimumSize(QtCore.QSize(49, 39))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveEntree.setIcon(icon3)
        self.btnSaveEntree.setIconSize(QtCore.QSize(22, 22))
        self.btnSaveEntree.setObjectName("btnSaveEntree")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.btnSaveEntree)
        self.dateEditEntreeDate = QtWidgets.QDateEdit(self.formFrame_3)
        self.dateEditEntreeDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEditEntreeDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEditEntreeDate.setCalendarPopup(False)
        self.dateEditEntreeDate.setObjectName("dateEditEntreeDate")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEditEntreeDate)
        self.labelEntreeError = QtWidgets.QLabel(self.formFrame_3)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelEntreeError.setFont(font)
        self.labelEntreeError.setWordWrap(True)
        self.labelEntreeError.setObjectName("labelEntreeError")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.labelEntreeError)
        self.entreeArticleID = QtWidgets.QLabel(self.formFrame_3)
        self.entreeArticleID.setText("")
        self.entreeArticleID.setObjectName("entreeArticleID")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.entreeArticleID)
        self.spBoxEntreePrix = QtWidgets.QDoubleSpinBox(self.formFrame_3)
        self.spBoxEntreePrix.setMinimumSize(QtCore.QSize(314, 34))
        self.spBoxEntreePrix.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spBoxEntreePrix.setMaximum(10000000000000.0)
        self.spBoxEntreePrix.setObjectName("spBoxEntreePrix")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spBoxEntreePrix)
        self.verticalLayout_3.addWidget(self.formFrame_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 261, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.EntreePage)
        self.SortiePage = QtWidgets.QWidget()
        self.SortiePage.setObjectName("SortiePage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SortiePage)
        self.verticalLayout_5.setContentsMargins(10, 15, 10, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.SortiePage)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spBoxSortiePrix = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spBoxSortiePrix.setEnabled(False)
        self.spBoxSortiePrix.setMinimumSize(QtCore.QSize(314, 34))
        self.spBoxSortiePrix.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spBoxSortiePrix.setMaximum(1e+16)
        self.spBoxSortiePrix.setObjectName("spBoxSortiePrix")
        self.gridLayout.addWidget(self.spBoxSortiePrix, 3, 1, 1, 1)
        self.lineEditSortieCode = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditSortieCode.setEnabled(False)
        self.lineEditSortieCode.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditSortieCode.setReadOnly(True)
        self.lineEditSortieCode.setObjectName("lineEditSortieCode")
        self.gridLayout.addWidget(self.lineEditSortieCode, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setMinimumSize(QtCore.QSize(85, 0))
        self.label_27.setMaximumSize(QtCore.QSize(79, 30))
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setMinimumSize(QtCore.QSize(85, 0))
        self.label_25.setMaximumSize(QtCore.QSize(79, 30))
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 0, 1, 1)
        self.dateEditSortieDate = QtWidgets.QDateEdit(self.frame_2)
        self.dateEditSortieDate.setWrapping(False)
        self.dateEditSortieDate.setFrame(True)
        self.dateEditSortieDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEditSortieDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditSortieDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEditSortieDate.setCalendarPopup(False)
        self.dateEditSortieDate.setObjectName("dateEditSortieDate")
        self.gridLayout.addWidget(self.dateEditSortieDate, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 0, 1, 1)
        self.btnSaveSortie = QtWidgets.QPushButton(self.frame_2)
        self.btnSaveSortie.setMinimumSize(QtCore.QSize(49, 39))
        self.btnSaveSortie.setIcon(icon3)
        self.btnSaveSortie.setIconSize(QtCore.QSize(22, 22))
        self.btnSaveSortie.setObjectName("btnSaveSortie")
        self.gridLayout.addWidget(self.btnSaveSortie, 5, 1, 1, 1)
        self.spBoxSortieQte = QtWidgets.QSpinBox(self.frame_2)
        self.spBoxSortieQte.setMinimumSize(QtCore.QSize(314, 34))
        self.spBoxSortieQte.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spBoxSortieQte.setMinimum(1)
        self.spBoxSortieQte.setMaximum(1000000000)
        self.spBoxSortieQte.setObjectName("spBoxSortieQte")
        self.gridLayout.addWidget(self.spBoxSortieQte, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setMinimumSize(QtCore.QSize(85, 0))
        self.label_26.setMaximumSize(QtCore.QSize(79, 30))
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 2, 0, 1, 1)
        self.labelSortieError = QtWidgets.QLabel(self.frame_2)
        self.labelSortieError.setObjectName("labelSortieError")
        self.gridLayout.addWidget(self.labelSortieError, 4, 1, 1, 1)
        self.sortieArticleID = QtWidgets.QLabel(self.frame_2)
        self.sortieArticleID.setText("")
        self.sortieArticleID.setObjectName("sortieArticleID")
        self.gridLayout.addWidget(self.sortieArticleID, 4, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 304, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.SortiePage)
        self.ConfirmPage = QtWidgets.QWidget()
        self.ConfirmPage.setObjectName("ConfirmPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ConfirmPage)
        self.verticalLayout_6.setContentsMargins(10, 15, 10, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelConfirmItemID = QtWidgets.QLabel(self.ConfirmPage)
        self.labelConfirmItemID.setText("")
        self.labelConfirmItemID.setObjectName("labelConfirmItemID")
        self.verticalLayout_6.addWidget(self.labelConfirmItemID)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.confirmLabelMessage = QtWidgets.QLabel(self.ConfirmPage)
        self.confirmLabelMessage.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.confirmLabelMessage.setFont(font)
        self.confirmLabelMessage.setStyleSheet("padding: 10px 0;")
        self.confirmLabelMessage.setWordWrap(True)
        self.confirmLabelMessage.setObjectName("confirmLabelMessage")
        self.verticalLayout_6.addWidget(self.confirmLabelMessage)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.frame_3 = QtWidgets.QFrame(self.ConfirmPage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonCancel = QtWidgets.QPushButton(self.frame_3)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.buttonConfirm = QtWidgets.QPushButton(self.frame_3)
        self.buttonConfirm.setObjectName("buttonConfirm")
        self.horizontalLayout.addWidget(self.buttonConfirm)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.ConfirmPage)
        self.NewUserPage = QtWidgets.QWidget()
        self.NewUserPage.setObjectName("NewUserPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.NewUserPage)
        self.verticalLayout_8.setContentsMargins(10, 15, 10, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.NewUserPage)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setHorizontalSpacing(30)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEditNewUsername = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewUsername.setObjectName("lineEditNewUsername")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditNewUsername)
        self.nomUtilisateurLabel = QtWidgets.QLabel(self.frame_4)
        self.nomUtilisateurLabel.setObjectName("nomUtilisateurLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nomUtilisateurLabel)
        self.lineEditNewFName = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewFName.setObjectName("lineEditNewFName")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditNewFName)
        self.prNomUtilisateurLabel = QtWidgets.QLabel(self.frame_4)
        self.prNomUtilisateurLabel.setObjectName("prNomUtilisateurLabel")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.prNomUtilisateurLabel)
        self.lineEditNewLName = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewLName.setObjectName("lineEditNewLName")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditNewLName)
        self.emailLabel = QtWidgets.QLabel(self.frame_4)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.lineEditNewEmail = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewEmail.setObjectName("lineEditNewEmail")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditNewEmail)
        self.posteDeTravailleLabel = QtWidgets.QLabel(self.frame_4)
        self.posteDeTravailleLabel.setObjectName("posteDeTravailleLabel")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.posteDeTravailleLabel)
        self.lineEditNewPTravaille = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewPTravaille.setObjectName("lineEditNewPTravaille")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditNewPTravaille)
        self.groupeLabel = QtWidgets.QLabel(self.frame_4)
        self.groupeLabel.setObjectName("groupeLabel")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.groupeLabel)
        self.cbBoxNewGroup = QtWidgets.QComboBox(self.frame_4)
        self.cbBoxNewGroup.setObjectName("cbBoxNewGroup")
        self.cbBoxNewGroup.addItem("")
        self.cbBoxNewGroup.addItem("")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cbBoxNewGroup)
        self.labelAddUserErrors = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAddUserErrors.sizePolicy().hasHeightForWidth())
        self.labelAddUserErrors.setSizePolicy(sizePolicy)
        self.labelAddUserErrors.setStyleSheet("c")
        self.labelAddUserErrors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelAddUserErrors.setWordWrap(True)
        self.labelAddUserErrors.setObjectName("labelAddUserErrors")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.labelAddUserErrors)
        self.buttonSaveNewUser = QtWidgets.QPushButton(self.frame_4)
        self.buttonSaveNewUser.setIconSize(QtCore.QSize(22, 22))
        self.buttonSaveNewUser.setObjectName("buttonSaveNewUser")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.buttonSaveNewUser)
        self.motPassLabel = QtWidgets.QLabel(self.frame_4)
        self.motPassLabel.setObjectName("motPassLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.motPassLabel)
        self.lineEditNewPassword = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditNewPassword.setObjectName("lineEditNewPassword")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditNewPassword)
        self.retapeMotPassLabel = QtWidgets.QLabel(self.frame_4)
        self.retapeMotPassLabel.setObjectName("retapeMotPassLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.retapeMotPassLabel)
        self.lineEditNewRePass = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditNewRePass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditNewRePass.setObjectName("lineEditNewRePass")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditNewRePass)
        self.verticalLayout_8.addWidget(self.frame_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.NewUserPage)
        self.EditUserPage = QtWidgets.QWidget()
        self.EditUserPage.setObjectName("EditUserPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.EditUserPage)
        self.verticalLayout_9.setContentsMargins(10, 15, 10, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.EditUserPage)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setHorizontalSpacing(20)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setObjectName("label_30")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEditEditUsername = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditEditUsername.setObjectName("lineEditEditUsername")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditEditUsername)
        self.nomUtilisateurLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.nomUtilisateurLabel_2.setObjectName("nomUtilisateurLabel_2")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nomUtilisateurLabel_2)
        self.lineEditEditFName = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditEditFName.setObjectName("lineEditEditFName")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditEditFName)
        self.prNomUtilisateurLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.prNomUtilisateurLabel_2.setObjectName("prNomUtilisateurLabel_2")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.prNomUtilisateurLabel_2)
        self.lineEditEditLName = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditEditLName.setObjectName("lineEditEditLName")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditEditLName)
        self.emailLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.emailLabel_2)
        self.lineEditEditEmail = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditEditEmail.setObjectName("lineEditEditEmail")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditEditEmail)
        self.posteDeTravailleLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.posteDeTravailleLabel_2.setObjectName("posteDeTravailleLabel_2")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.posteDeTravailleLabel_2)
        self.lineEditEditPTravaille = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditEditPTravaille.setObjectName("lineEditEditPTravaille")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditEditPTravaille)
        self.groupeLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.groupeLabel_2.setObjectName("groupeLabel_2")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.groupeLabel_2)
        self.cbBoxEditGroup = QtWidgets.QComboBox(self.frame_5)
        self.cbBoxEditGroup.setObjectName("cbBoxEditGroup")
        self.cbBoxEditGroup.addItem("")
        self.cbBoxEditGroup.addItem("")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cbBoxEditGroup)
        self.buttonSaveEditUser = QtWidgets.QPushButton(self.frame_5)
        self.buttonSaveEditUser.setIconSize(QtCore.QSize(22, 22))
        self.buttonSaveEditUser.setObjectName("buttonSaveEditUser")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.buttonSaveEditUser)
        self.labelEditUserErrors = QtWidgets.QLabel(self.frame_5)
        self.labelEditUserErrors.setStyleSheet("c")
        self.labelEditUserErrors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelEditUserErrors.setWordWrap(True)
        self.labelEditUserErrors.setObjectName("labelEditUserErrors")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelEditUserErrors)
        self.labelEditUserID = QtWidgets.QLabel(self.frame_5)
        self.labelEditUserID.setText("")
        self.labelEditUserID.setObjectName("labelEditUserID")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelEditUserID)
        self.verticalLayout_9.addWidget(self.frame_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 209, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.EditUserPage)
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.LoginPage)
        self.verticalLayout_10.setContentsMargins(10, 15, 10, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_6 = QtWidgets.QFrame(self.LoginPage)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setHorizontalSpacing(15)
        self.formLayout_7.setVerticalSpacing(6)
        self.formLayout_7.setObjectName("formLayout_7")
        self.usernameLoginLabel = QtWidgets.QLabel(self.frame_6)
        self.usernameLoginLabel.setObjectName("usernameLoginLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLoginLabel)
        self.lineEditUsernameLogin = QtWidgets.QLineEdit(self.frame_6)
        self.lineEditUsernameLogin.setObjectName("lineEditUsernameLogin")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditUsernameLogin)
        self.passwordLabel = QtWidgets.QLabel(self.frame_6)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.lineEditPasswordLogin = QtWidgets.QLineEdit(self.frame_6)
        self.lineEditPasswordLogin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPasswordLogin.setObjectName("lineEditPasswordLogin")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPasswordLogin)
        self.labelLoginErrors = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLoginErrors.sizePolicy().hasHeightForWidth())
        self.labelLoginErrors.setSizePolicy(sizePolicy)
        self.labelLoginErrors.setWordWrap(True)
        self.labelLoginErrors.setObjectName("labelLoginErrors")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelLoginErrors)
        self.buttonLogin = QtWidgets.QPushButton(self.frame_6)
        self.buttonLogin.setIconSize(QtCore.QSize(25, 25))
        self.buttonLogin.setObjectName("buttonLogin")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonLogin)
        self.verticalLayout_10.addWidget(self.frame_6)
        spacerItem9 = QtWidgets.QSpacerItem(20, 271, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.LoginPage)
        self.ChangePasswordPage = QtWidgets.QWidget()
        self.ChangePasswordPage.setObjectName("ChangePasswordPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ChangePasswordPage)
        self.verticalLayout_12.setContentsMargins(10, 15, 10, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_7 = QtWidgets.QFrame(self.ChangePasswordPage)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame_7)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setHorizontalSpacing(15)
        self.formLayout_8.setVerticalSpacing(6)
        self.formLayout_8.setObjectName("formLayout_8")
        self.usernameLoginLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.usernameLoginLabel_2.setObjectName("usernameLoginLabel_2")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLoginLabel_2)
        self.lineEditChangePass = QtWidgets.QLineEdit(self.frame_7)
        self.lineEditChangePass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditChangePass.setObjectName("lineEditChangePass")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditChangePass)
        self.passwordLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.passwordLabel_2.setObjectName("passwordLabel_2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_2)
        self.lineEditReChangePass = QtWidgets.QLineEdit(self.frame_7)
        self.lineEditReChangePass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditReChangePass.setObjectName("lineEditReChangePass")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditReChangePass)
        self.labelChangePassErrors = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelChangePassErrors.sizePolicy().hasHeightForWidth())
        self.labelChangePassErrors.setSizePolicy(sizePolicy)
        self.labelChangePassErrors.setWordWrap(True)
        self.labelChangePassErrors.setObjectName("labelChangePassErrors")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelChangePassErrors)
        self.buttonChangePassword = QtWidgets.QPushButton(self.frame_7)
        self.buttonChangePassword.setIconSize(QtCore.QSize(25, 25))
        self.buttonChangePassword.setObjectName("buttonChangePassword")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonChangePassword)
        self.labelChangePasswordUserID = QtWidgets.QLabel(self.frame_7)
        self.labelChangePasswordUserID.setText("")
        self.labelChangePasswordUserID.setObjectName("labelChangePasswordUserID")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelChangePasswordUserID)
        self.verticalLayout_12.addWidget(self.frame_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem10)
        self.stackedWidget.addWidget(self.ChangePasswordPage)
        self.NewCommandPage = QtWidgets.QWidget()
        self.NewCommandPage.setObjectName("NewCommandPage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.NewCommandPage)
        self.verticalLayout_11.setContentsMargins(10, 15, 10, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_8 = QtWidgets.QFrame(self.NewCommandPage)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_34 = QtWidgets.QLabel(self.frame_8)
        self.label_34.setMinimumSize(QtCore.QSize(85, 0))
        self.label_34.setMaximumSize(QtCore.QSize(79, 30))
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 2, 0, 1, 1)
        self.btnSaveCommand = QtWidgets.QPushButton(self.frame_8)
        self.btnSaveCommand.setMinimumSize(QtCore.QSize(49, 39))
        self.btnSaveCommand.setIcon(icon3)
        self.btnSaveCommand.setIconSize(QtCore.QSize(22, 22))
        self.btnSaveCommand.setObjectName("btnSaveCommand")
        self.gridLayout_2.addWidget(self.btnSaveCommand, 4, 1, 1, 1)
        self.spBoxCommandQte = QtWidgets.QSpinBox(self.frame_8)
        self.spBoxCommandQte.setMinimumSize(QtCore.QSize(314, 34))
        self.spBoxCommandQte.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spBoxCommandQte.setMinimum(1)
        self.spBoxCommandQte.setMaximum(1000000000)
        self.spBoxCommandQte.setObjectName("spBoxCommandQte")
        self.gridLayout_2.addWidget(self.spBoxCommandQte, 2, 1, 1, 1)
        self.labelCommandError = QtWidgets.QLabel(self.frame_8)
        self.labelCommandError.setObjectName("labelCommandError")
        self.gridLayout_2.addWidget(self.labelCommandError, 3, 1, 1, 1)
        self.commandArticleID = QtWidgets.QLabel(self.frame_8)
        self.commandArticleID.setText("")
        self.commandArticleID.setObjectName("commandArticleID")
        self.gridLayout_2.addWidget(self.commandArticleID, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineEditCommandCode = QtWidgets.QLineEdit(self.frame_8)
        self.lineEditCommandCode.setEnabled(False)
        self.lineEditCommandCode.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditCommandCode.setReadOnly(True)
        self.lineEditCommandCode.setObjectName("lineEditCommandCode")
        self.gridLayout_2.addWidget(self.lineEditCommandCode, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_8)
        self.label_32.setMinimumSize(QtCore.QSize(85, 0))
        self.label_32.setMaximumSize(QtCore.QSize(79, 30))
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 1, 0, 1, 1)
        self.dateEditCommandDate = QtWidgets.QDateEdit(self.frame_8)
        self.dateEditCommandDate.setWrapping(False)
        self.dateEditCommandDate.setFrame(True)
        self.dateEditCommandDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEditCommandDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditCommandDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEditCommandDate.setCalendarPopup(False)
        self.dateEditCommandDate.setObjectName("dateEditCommandDate")
        self.gridLayout_2.addWidget(self.dateEditCommandDate, 0, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_8)
        spacerItem11 = QtWidgets.QSpacerItem(20, 353, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.stackedWidget.addWidget(self.NewCommandPage)
        self.EditCommandPage = QtWidgets.QWidget()
        self.EditCommandPage.setObjectName("EditCommandPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.EditCommandPage)
        self.verticalLayout_15.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_10 = QtWidgets.QFrame(self.EditCommandPage)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnEditCommand = QtWidgets.QPushButton(self.frame_10)
        self.btnEditCommand.setText("")
        self.btnEditCommand.setIconSize(QtCore.QSize(25, 25))
        self.btnEditCommand.setObjectName("btnEditCommand")
        self.horizontalLayout_3.addWidget(self.btnEditCommand)
        spacerItem12 = QtWidgets.QSpacerItem(382, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.btnSaveEditCommand = QtWidgets.QPushButton(self.frame_10)
        self.btnSaveEditCommand.setEnabled(False)
        self.btnSaveEditCommand.setText("")
        self.btnSaveEditCommand.setIconSize(QtCore.QSize(25, 25))
        self.btnSaveEditCommand.setObjectName("btnSaveEditCommand")
        self.horizontalLayout_3.addWidget(self.btnSaveEditCommand)
        self.verticalLayout_15.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.EditCommandPage)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spBoxEditCommandQte = QtWidgets.QSpinBox(self.frame_9)
        self.spBoxEditCommandQte.setEnabled(False)
        self.spBoxEditCommandQte.setMinimumSize(QtCore.QSize(314, 34))
        self.spBoxEditCommandQte.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spBoxEditCommandQte.setMinimum(1)
        self.spBoxEditCommandQte.setMaximum(1000000000)
        self.spBoxEditCommandQte.setObjectName("spBoxEditCommandQte")
        self.gridLayout_3.addWidget(self.spBoxEditCommandQte, 2, 1, 1, 1)
        self.labelEditCommandError = QtWidgets.QLabel(self.frame_9)
        self.labelEditCommandError.setObjectName("labelEditCommandError")
        self.gridLayout_3.addWidget(self.labelEditCommandError, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_9)
        self.label_35.setMinimumSize(QtCore.QSize(85, 0))
        self.label_35.setMaximumSize(QtCore.QSize(79, 30))
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 2, 0, 1, 1)
        self.dateEditCommandDateEdit = QtWidgets.QDateEdit(self.frame_9)
        self.dateEditCommandDateEdit.setEnabled(False)
        self.dateEditCommandDateEdit.setWrapping(False)
        self.dateEditCommandDateEdit.setFrame(True)
        self.dateEditCommandDateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEditCommandDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditCommandDateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEditCommandDateEdit.setCalendarPopup(False)
        self.dateEditCommandDateEdit.setObjectName("dateEditCommandDateEdit")
        self.gridLayout_3.addWidget(self.dateEditCommandDateEdit, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_9)
        self.label_37.setMinimumSize(QtCore.QSize(85, 0))
        self.label_37.setMaximumSize(QtCore.QSize(79, 30))
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 1, 0, 1, 1)
        self.editCommandCmdID = QtWidgets.QLabel(self.frame_9)
        self.editCommandCmdID.setText("")
        self.editCommandCmdID.setObjectName("editCommandCmdID")
        self.gridLayout_3.addWidget(self.editCommandCmdID, 3, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_9)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 0, 0, 1, 1)
        self.lineEditEditCommandCode = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditEditCommandCode.setEnabled(False)
        self.lineEditEditCommandCode.setMinimumSize(QtCore.QSize(314, 34))
        self.lineEditEditCommandCode.setReadOnly(True)
        self.lineEditEditCommandCode.setObjectName("lineEditEditCommandCode")
        self.gridLayout_3.addWidget(self.lineEditEditCommandCode, 1, 1, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_9)
        spacerItem13 = QtWidgets.QSpacerItem(20, 339, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem13)
        self.stackedWidget.addWidget(self.EditCommandPage)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.MainWidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(12)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.closeAppBtn.setToolTip(_translate("Dialog", "Close"))
        self.titleLabel.setText(_translate("Dialog", "Ajouté un Article"))
        self.label_28.setText(_translate("Dialog", "Catégory Nom"))
        self.lineEditCatName.setPlaceholderText(_translate("Dialog", "Category Name"))
        self.labelCategoryError.setText(_translate("Dialog", "Error Label"))
        self.btnSaveNewCat.setText(_translate("Dialog", "Ajouter"))
        self.label_31.setText(_translate("Dialog", "Catégory Nom"))
        self.labelEmptyCodeError.setText(_translate("Dialog", "Error Label"))
        self.btnSearchEmptyCode.setText(_translate("Dialog", "Recherche"))
        self.label_9.setText(_translate("Dialog", "Category"))
        self.label.setText(_translate("Dialog", "Code"))
        self.lineEditCodeNew.setPlaceholderText(_translate("Dialog", "Code Article"))
        self.label_2.setText(_translate("Dialog", "Designation"))
        self.lineEditDesigNew.setPlaceholderText(_translate("Dialog", "Designation"))
        self.label_3.setText(_translate("Dialog", "Reference"))
        self.lineEditRefNew.setPlaceholderText(_translate("Dialog", "Référence de l\'Article"))
        self.label_4.setText(_translate("Dialog", "U Mesure"))
        self.lineEditUMNew.setPlaceholderText(_translate("Dialog", "Unité de Mésure (PCS,...)"))
        self.label_5.setText(_translate("Dialog", "Emplacement"))
        self.lineEditEmpNew.setPlaceholderText(_translate("Dialog", "Emplacement d\'Article"))
        self.label_6.setText(_translate("Dialog", "Quantite"))
        self.label_7.setText(_translate("Dialog", "Prix"))
        self.label_10.setText(_translate("Dialog", "Observation"))
        self.textEditObsNew.setPlaceholderText(_translate("Dialog", "Observation"))
        self.btnSaveNewArticle.setText(_translate("Dialog", "Enregistrer"))
        self.labelNewError.setText(_translate("Dialog", "Label New Article Errors"))
        self.btnEditArticle.setToolTip(_translate("Dialog", "Modifier l\'Article"))
        self.btnSaveEditArticle.setToolTip(_translate("Dialog", "Enregistrer les modification"))
        self.label_8.setText(_translate("Dialog", "Category"))
        self.label_11.setText(_translate("Dialog", "Code"))
        self.label_12.setText(_translate("Dialog", "Designation"))
        self.label_13.setText(_translate("Dialog", "Reference"))
        self.label_14.setText(_translate("Dialog", "Emplacement"))
        self.label_15.setText(_translate("Dialog", "U-Mesure"))
        self.label_16.setText(_translate("Dialog", "Quantité"))
        self.label_17.setText(_translate("Dialog", "Prix"))
        self.label_18.setText(_translate("Dialog", "Valeur"))
        self.label_19.setText(_translate("Dialog", "Observation"))
        self.labelEditError.setText(_translate("Dialog", "Label Edit Article Errors"))
        self.label_20.setText(_translate("Dialog", "Date"))
        self.label_21.setText(_translate("Dialog", "Code"))
        self.label_22.setText(_translate("Dialog", "Quantité"))
        self.label_23.setText(_translate("Dialog", "Prix"))
        self.btnSaveEntree.setText(_translate("Dialog", "   Entree"))
        self.dateEditEntreeDate.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.labelEntreeError.setText(_translate("Dialog", "Label Error"))
        self.label_27.setText(_translate("Dialog", "Prix"))
        self.label_25.setText(_translate("Dialog", "Code"))
        self.label_24.setText(_translate("Dialog", "Date"))
        self.btnSaveSortie.setText(_translate("Dialog", "   Sortie"))
        self.label_26.setText(_translate("Dialog", "Quantité"))
        self.labelSortieError.setText(_translate("Dialog", "Label Error"))
        self.confirmLabelMessage.setText(_translate("Dialog", "Are you sure "))
        self.buttonCancel.setText(_translate("Dialog", "Annuler"))
        self.buttonConfirm.setText(_translate("Dialog", "Confirm"))
        self.label_29.setText(_translate("Dialog", "Username"))
        self.lineEditNewUsername.setPlaceholderText(_translate("Dialog", "Username"))
        self.nomUtilisateurLabel.setText(_translate("Dialog", "Nom"))
        self.lineEditNewFName.setPlaceholderText(_translate("Dialog", "First Name"))
        self.prNomUtilisateurLabel.setText(_translate("Dialog", "Prénom"))
        self.lineEditNewLName.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.emailLabel.setText(_translate("Dialog", "Email"))
        self.lineEditNewEmail.setPlaceholderText(_translate("Dialog", "Email"))
        self.posteDeTravailleLabel.setText(_translate("Dialog", "P. Travaille"))
        self.lineEditNewPTravaille.setPlaceholderText(_translate("Dialog", "Poste de Travaille"))
        self.groupeLabel.setText(_translate("Dialog", "Groupe"))
        self.cbBoxNewGroup.setItemText(0, _translate("Dialog", "Admin"))
        self.cbBoxNewGroup.setItemText(1, _translate("Dialog", "Other"))
        self.labelAddUserErrors.setText(_translate("Dialog", "Add User Errors"))
        self.buttonSaveNewUser.setText(_translate("Dialog", "Enregistrer"))
        self.motPassLabel.setText(_translate("Dialog", "Mot Pass"))
        self.lineEditNewPassword.setPlaceholderText(_translate("Dialog", "Mot de Passe"))
        self.retapeMotPassLabel.setText(_translate("Dialog", "Retape Mot Pass"))
        self.lineEditNewRePass.setPlaceholderText(_translate("Dialog", "Retapé le Mot de Pass"))
        self.label_30.setText(_translate("Dialog", "Username"))
        self.lineEditEditUsername.setPlaceholderText(_translate("Dialog", "Username"))
        self.nomUtilisateurLabel_2.setText(_translate("Dialog", "Nom"))
        self.lineEditEditFName.setPlaceholderText(_translate("Dialog", "First Name"))
        self.prNomUtilisateurLabel_2.setText(_translate("Dialog", "Prénom"))
        self.lineEditEditLName.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.emailLabel_2.setText(_translate("Dialog", "Email"))
        self.lineEditEditEmail.setPlaceholderText(_translate("Dialog", "Email"))
        self.posteDeTravailleLabel_2.setText(_translate("Dialog", "P. Travaille"))
        self.lineEditEditPTravaille.setPlaceholderText(_translate("Dialog", "Poste de Travaille"))
        self.groupeLabel_2.setText(_translate("Dialog", "Groupe"))
        self.cbBoxEditGroup.setItemText(0, _translate("Dialog", "Admin"))
        self.cbBoxEditGroup.setItemText(1, _translate("Dialog", "Other"))
        self.buttonSaveEditUser.setText(_translate("Dialog", "Enregistrer"))
        self.labelEditUserErrors.setText(_translate("Dialog", "Edit User Errors"))
        self.usernameLoginLabel.setText(_translate("Dialog", "Username"))
        self.lineEditUsernameLogin.setPlaceholderText(_translate("Dialog", "Username"))
        self.passwordLabel.setText(_translate("Dialog", "Password"))
        self.lineEditPasswordLogin.setPlaceholderText(_translate("Dialog", "Password"))
        self.labelLoginErrors.setText(_translate("Dialog", "Label Error"))
        self.buttonLogin.setText(_translate("Dialog", "Login"))
        self.usernameLoginLabel_2.setText(_translate("Dialog", "New Password"))
        self.lineEditChangePass.setPlaceholderText(_translate("Dialog", "New Password"))
        self.passwordLabel_2.setText(_translate("Dialog", "Re-Password"))
        self.lineEditReChangePass.setPlaceholderText(_translate("Dialog", "Retype Password"))
        self.labelChangePassErrors.setText(_translate("Dialog", "Label Error"))
        self.buttonChangePassword.setText(_translate("Dialog", "Change Password"))
        self.label_34.setText(_translate("Dialog", "Quantité"))
        self.btnSaveCommand.setText(_translate("Dialog", "  Commande"))
        self.labelCommandError.setText(_translate("Dialog", "Label Error"))
        self.label_33.setText(_translate("Dialog", "Date"))
        self.label_32.setText(_translate("Dialog", "Code"))
        self.labelEditCommandError.setText(_translate("Dialog", "Label Error"))
        self.label_35.setText(_translate("Dialog", "Quantité"))
        self.label_37.setText(_translate("Dialog", "Code"))
        self.label_36.setText(_translate("Dialog", "Date"))
import resource_rc
